const {plantFor,pick,id,page,ok,fail}=require('./helpers');
const {nextDue}=require('../services/careService');
exports.resource=(name,fields)=>{const Model=require(`../models/${name}`);const find=async req=>{await plantFor(req);const record=await Model.findOne({_id:id(req.params.recordId),owner:req.user._id,plant:req.params.plantId});if(!record)throw fail(404,'Record not found.');return record;};return {
list:async(req,res)=>{await plantFor(req);const {limit,skip}=page(req);ok(res,await Model.find({owner:req.user._id,plant:req.params.plantId}).sort({createdAt:-1}).skip(skip).limit(limit));},
create:async(req,res)=>{await plantFor(req);const data=pick(req.body,fields);if(name==='CalculatorRecord'){try{data.result=require('../services/calculationService').calculate(data.mode,data.inputs||{});}catch(error){throw fail(400,error.message);}}if(name==='RecoveryObservation'&&data.scan){const scan=await require('../models/Scan').findOne({_id:id(data.scan),owner:req.user._id,plant:req.params.plantId});if(!scan)throw fail(404,'Scan not found.');}if(name==='LightReading'&&(data.source==='webcam-estimate'?!Number.isFinite(data.brightness):!Number.isFinite(data.lux)))throw fail(400,'A valid light reading is required.');ok(res,await Model.create({...data,owner:req.user._id,plant:req.params.plantId}),201);},
update:async(req,res)=>{const record=await find(req);const changes=pick(req.body,fields);if(name==='CalculatorRecord'){try{changes.result=require('../services/calculationService').calculate(changes.mode||record.mode,changes.inputs||Object.fromEntries(record.inputs));}catch(error){throw fail(400,error.message);}}if(name==='RecoveryObservation'&&changes.scan){const scan=await require('../models/Scan').findOne({_id:id(changes.scan),owner:req.user._id,plant:req.params.plantId});if(!scan)throw fail(404,'Scan not found.');}Object.assign(record,changes);await record.save();ok(res,record);},
remove:async(req,res)=>{const record=await find(req);await record.deleteOne();ok(res,{deleted:true});},
complete:async(req,res)=>{const task=await find(req);const now=new Date();const record=await Model.findOneAndUpdate({_id:task._id,owner:req.user._id,updatedAt:task.updatedAt},{$set:{due:nextDue(task.due,task.frequency,now),lastCompleted:now},$push:{completions:now}},{returnDocument:'after',runValidators:true});if(!record)throw fail(409,'Task changed. Refresh before completing again.');ok(res,record);}
};};
