import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Box, Button, Card, Checkbox, Chip, FormControlLabel, MenuItem, Select, Stack, Step, StepLabel, Stepper, TextField, Typography } from '@mui/material'

const dateToday = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Calcutta', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date())
const stages = ['Planted', 'Establishing', 'Growing', 'Flowering', 'Harvest / maturity', 'Renewal / dormancy']
const nextSteps = ['Watch for emergence or signs that the transplant has settled in.', 'Look for new leaves and consistent growth.', 'Observe new growth and buds. Leafy crops can be harvested during this stage.', 'Look for fruit development where applicable; leafy plants can continue their growth cycle.', 'Record harvest or maturity, then plan the next cycle.', 'Watch for renewed growth or start a new planting cycle.']
const recovery = [
  ['Inspect the plant', 'Check both sides of leaves, stems, and soil. Note where symptoms appear and whether they are spreading.'],
  ['Identify the issue', 'Take a clear photo and compare symptoms. Confirm the cause before selecting a treatment.'],
  ['Apply a care plan', 'Record the chosen action. For any product, use its label instructions for this plant and issue.'],
  ['Recheck progress', 'Compare new photos with the original symptoms. If damage spreads, seek a plant specialist’s advice.'],
]
export default function ManagePlant({ plantId, plant }) {
  const key = `plantaexa-management-${plantId}`
  const [data, setData] = useState(() => { try { const saved = JSON.parse(localStorage.getItem(key)); if (saved && Number.isInteger(saved.stage) && saved.stage >= 0 && saved.stage < stages.length && Array.isArray(saved.tasks)) return saved } catch { /* Start a new management plan. */ } return { stage: 0, stageSet: false, condition: plant.status === 'Needs care' ? 'Concern detected' : 'Healthy', recoveryStep: 0, tasks: [], completed: [], treatment: '', followUp: '', milestones: [] } })
  const [message, setMessage] = useState('')
  const [taskName, setTaskName] = useState('Check soil moisture')
  const [taskDate, setTaskDate] = useState(dateToday())
  const update = changes => { const next = { ...data, ...changes }; setData(next); try { localStorage.setItem(key, JSON.stringify(next)); setMessage('Plan saved on this device.') } catch { setMessage('Plan updated for this visit; saving on this device failed.') } }
  const concerned = data.condition !== 'Healthy'
  const step = Math.min(data.recoveryStep || 0, recovery.length - 1)
  const tasks = data.tasks.filter(task => !task.done).sort((a, b) => a.date.localeCompare(b.date))
  const setStage = stage => update({ stage, stageSet: true, milestones: [{ stage: stages[stage], date: dateToday() }, ...(data.milestones || [])] })
  const done = task => update({ tasks: data.tasks.map(item => item.id === task.id ? { ...item, done: true } : item), completed: [{ title: task.title, date: dateToday() }, ...(data.completed || [])] })
  return <Box className="manage-plant">
    <Stack direction="row" alignItems="center" justifyContent="space-between" gap={1}><Typography variant="h6">{plant.name}’s care journey</Typography><Chip size="small" label={data.condition} color={concerned ? 'warning' : 'success'} /></Stack>
    <Card elevation={0} className={`manage-next ${concerned ? 'needs-care' : ''}`}><Typography className="manage-eyebrow">YOUR NEXT STEP</Typography><Typography variant="h6">{concerned ? recovery[step][0] : data.stageSet ? nextSteps[data.stage] : 'Set your plant’s current growth stage'}</Typography><Typography>{concerned ? recovery[step][1] : data.stageSet ? 'Keep its routine consistent and use the care agenda below to stay on track.' : 'Choose the stage below. Your next milestone and care journey will follow your selection.'}</Typography>{concerned && <Button component={Link} to="/farm/dashboard/scan" variant="contained">Scan plant / compare symptoms</Button>}</Card>
    <Card elevation={0} className="manage-section"><Typography variant="h6">Growth lifecycle</Typography><Select fullWidth size="small" value={data.stageSet ? data.stage : ''} displayEmpty onChange={event => setStage(Number(event.target.value))} inputProps={{ 'aria-label': 'Current growth stage' }}><MenuItem value="" disabled>Choose current stage</MenuItem>{stages.map((stage, index) => <MenuItem key={stage} value={index}>{stage}</MenuItem>)}</Select><Stepper orientation="vertical" activeStep={data.stageSet ? data.stage : -1}>{stages.map((stage, index) => <Step key={stage} completed={(data.milestones || []).some(item => item.stage === stage) && index !== data.stage}><StepLabel>{stage}{data.stageSet && index === data.stage && <Typography variant="caption" display="block">Current stage</Typography>}</StepLabel></Step>)}</Stepper>{data.stageSet && <Button variant="outlined" onClick={() => setStage((data.stage + 1) % stages.length)}>{data.stage === stages.length - 1 ? 'Start next cycle' : `Move to ${stages[data.stage + 1]}`}</Button>}<Typography className="manage-caption">Update stages when observed. Flowering and harvest stages can be skipped when they do not apply.</Typography></Card>
    <Card elevation={0} className="manage-section"><Typography variant="h6">Health & recovery plan</Typography><Select size="small" fullWidth value={data.condition} onChange={event => update({ condition: event.target.value, recoveryStep: 0 })} inputProps={{ 'aria-label': 'Plant health condition' }}>{['Healthy', 'Concern detected', 'Under treatment', 'Recovering'].map(condition => <MenuItem key={condition}>{condition}</MenuItem>)}</Select>{concerned ? <><Stepper orientation="vertical" activeStep={step}>{recovery.map(([title]) => <Step key={title}><StepLabel>{title}</StepLabel></Step>)}</Stepper><TextField size="small" fullWidth label="Chosen care action / treatment" multiline minRows={2} value={data.treatment} onChange={event => update({ treatment: event.target.value })} /><TextField size="small" fullWidth type="date" label="Recheck date" slotProps={{ inputLabel: { shrink: true } }} value={data.followUp} onChange={event => update({ followUp: event.target.value })} />{data.followUp && <Typography className="manage-caption">Recheck {data.followUp}{data.followUp <= dateToday() ? ' · Due now' : ''}. Compare symptoms and new growth.</Typography>}<Button variant="contained" disabled={step === 2 && (!data.treatment.trim() || !data.followUp)} onClick={() => step < 3 ? update({ recoveryStep: step + 1, condition: step === 2 ? 'Under treatment' : data.condition }) : update({ condition: 'Healthy', recoveryStep: 0 })}>{step < 3 ? 'Complete step & continue' : 'Recovered · return to routine'}</Button><Typography className="manage-caption">If symptoms persist, revisit identification and adjust the plan with a specialist.</Typography></> : <><Typography className="manage-caption">Continue routine checks. If you notice spots, pests, wilting, or unusual growth, select “Concern detected” to start the recovery workflow.</Typography><Button variant="outlined" onClick={() => update({ condition: 'Concern detected', recoveryStep: 0 })}>Report a health concern</Button></>}</Card>
    <Card elevation={0} className="manage-section"><Typography variant="h6">Care agenda</Typography>{tasks.length ? tasks.map(task => <Box key={task.id} className="manage-task"><FormControlLabel control={<Checkbox checked={false} onChange={() => done(task)} />} label={<><Typography>{task.title}</Typography><Typography variant="caption">{task.date}{task.date <= dateToday() ? ' · Due' : ''}</Typography></>} /></Box>) : <Typography className="manage-caption">Schedule your next care check.</Typography>}<Box component="form" className="manage-task-form" onSubmit={event => { event.preventDefault(); update({ tasks: [...data.tasks, { id: crypto.randomUUID(), title: taskName, date: taskDate }] }) }}><Select size="small" value={taskName} onChange={event => setTaskName(event.target.value)} inputProps={{ 'aria-label': 'Care task' }}>{['Check soil moisture', 'Check leaves and pests', 'Fertilize', 'Prune', 'Repot', 'Re-scan health', 'Harvest'].map(task => <MenuItem key={task}>{task}</MenuItem>)}</Select><TextField size="small" type="date" required value={taskDate} onChange={event => setTaskDate(event.target.value)} slotProps={{ htmlInput: { 'aria-label': 'Task date' } }} /><Button type="submit" variant="contained">Schedule care</Button></Box>{!!data.completed?.length && <Typography className="manage-caption">Last completed: {data.completed[0].title} · {data.completed[0].date}</Typography>}</Card>
    <Typography role="status" className="manage-caption">{message || 'Your plan is saved per plant on this device.'}</Typography>
  </Box>
}
