import PhoneCameraDialog from './PhoneCameraDialog'
import { useEffect, useRef, useState } from 'react'
import { api, runScan, scanHistory } from '../services/api'
import { Alert, Box, Button, Dialog, DialogContent, DialogTitle, IconButton, LinearProgress, Typography } from '@mui/material'
import { MdOutlineCameraAlt, MdOutlinePhotoLibrary, MdOutlineHealthAndSafety, MdClose } from 'react-icons/md'
export default function RecoveryCheck({ plantId, plant, onComplete, completedTasks = 0, totalTasks = 4, open, onClose }) {
  const [photo, setPhoto] = useState(''), [cameraOn, setCameraOn] = useState(false), [error, setError] = useState(''), [progress, setProgress] = useState(0), [scanning, setScanning] = useState(false), [done, setDone] = useState(false)
  const recordCheck = async () => {
    try { await runScan({plantId,kind:'Recovery check',images:[photo],notes:plant.notes || ''}); const scans=await api(`/plants/${plantId}/scans`); setDone(true);onComplete?.({history:scans.map(scanHistory),photo}) }catch(err){setError(err.message)}finally{setScanning(false)}
  }
  const timer = useRef(null), attempt = useRef(0)
  useEffect(() => { if (!open) { attempt.current++; clearInterval(timer.current) } return () => { attempt.current++; clearInterval(timer.current) } }, [open])
  const camera = () => { setCameraOn(true); setDone(false); setError('') }
  const capture = image => { setPhoto(image); setCameraOn(false); setDone(false); setError('') }
  const choose = event => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 10*1024*1024) { setError('Choose a JPG, PNG or WebP under 10 MB.'); return }; setCameraOn(false); const reader = new FileReader(); reader.onload = () => { if (!open) return; setPhoto(reader.result); setDone(false); setError('') }; reader.readAsDataURL(file) }
  const scan = () => { setScanning(true); setProgress(0); setDone(false); let elapsed = 0; timer.current = setInterval(() => { elapsed++; setProgress(elapsed/9*100); if (elapsed === 9) { clearInterval(timer.current); recordCheck() } },1000) }
  const close = () => { attempt.current++; clearInterval(timer.current); setScanning(false); setCameraOn(false); onClose() }
  return <Dialog open={open} onClose={close} fullWidth maxWidth="sm"><DialogTitle sx={{ display:'flex', justifyContent:'space-between', alignItems:'center' }}>Check on recovery<IconButton aria-label="Close recovery check" onClick={close}><MdClose /></IconButton></DialogTitle><DialogContent><Box className="recovery-check"><span className="recovery-check-icon"><MdOutlineHealthAndSafety /></span><Typography component="h3">Review {plant.name}’s recovery</Typography><Typography>Take clear photos of the affected leaves or stems to review changes.</Typography>{photo && <img src={photo} alt="Plant recovery photo" />}<PhoneCameraDialog open={open && cameraOn} onClose={()=>setCameraOn(false)} onCapture={capture} />{!scanning && <Box className="recovery-photo-actions"><Button variant="contained" startIcon={<MdOutlineCameraAlt />} onClick={camera}>Take photo</Button><Button variant="outlined" component="label" startIcon={<MdOutlinePhotoLibrary />}>From gallery<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={choose} /></Button></Box>}{photo && !cameraOn && !done && <Button variant="contained" disabled={scanning} onClick={scan}>{scanning ? 'Checking recovery…' : 'Run demo recovery check'}</Button>}{scanning && <Box sx={{ width:'100%' }} role="status"><Typography>{progress < 34 ? 'Preparing your photo' : progress < 67 ? 'Reviewing the sample recovery flow' : 'Preparing the demo report'}</Typography><LinearProgress variant="determinate" value={progress} sx={{ mt:1 }} /></Box>}{error && <Alert severity="info">{error}</Alert>}<Typography variant="caption">Photos stay on this device. Recovery checking currently uses sample results.</Typography></Box></DialogContent></Dialog>
}
