import {useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {Box,Typography,TextField,Button,Alert} from '@mui/material'
import Navbar from '../components/Navbar'
import {useAuth} from '../context/AuthContext'
import {apiBase} from '../services/api'
import {readAuthResponse} from '../services/authResponse'
export default function DoctorSignup(){
 const navigate=useNavigate(),{login}=useAuth(),[form,setForm]=useState({fullName:'',email:'',password:'',confirmPassword:'',specialty:'',qualifications:'',location:'',languages:'',experienceYears:''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async event=>{event.preventDefault();setError('');setBusy(true);try{const response=await fetch(apiBase+'/doctor/signup',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,languages:form.languages.split(',').map(value=>value.trim()).filter(Boolean),experienceYears:form.experienceYears===''?undefined:Number(form.experienceYears)})});const result=await readAuthResponse(response);login(result.data,result.token);navigate('/dr/dashboard')}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <main className="signup-page"><Navbar/><Box sx={{maxWidth:760,mx:'auto',my:4,p:{xs:2,sm:4},borderRadius:4,bgcolor:'#fff',border:'1px solid #d7e5ea',color:'#172846'}}><Typography variant="h4" fontWeight={700}>Register as a plant expert</Typography><Typography sx={{mt:1,mb:3,color:'#648097'}}>Create your doctor account and professional profile.</Typography>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Box component="form" onSubmit={submit} sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr'},gap:2}}>{[['fullName','Full name',true],['email','Email',true],['specialty','Specialty',true],['qualifications','Qualifications'],['location','Location'],['languages','Languages (comma separated)'],['experienceYears','Years of experience'],['password','Password',true],['confirmPassword','Confirm password',true]].map(([name,label,required])=><TextField key={name} label={label} required={!!required} value={form[name]} disabled={busy} type={name.includes('assword')?'password':name==='email'?'email':name==='experienceYears'?'number':'text'} onChange={event=>setForm(value=>({...value,[name]:event.target.value}))} slotProps={{htmlInput:{...(name.includes('assword')?{minLength:8}:{}),...(name==='experienceYears'?{min:0,max:80}:{}),maxLength:500}}} size="small"/>)}<Button type="submit" variant="contained" disabled={busy} sx={{gridColumn:'1 / -1',py:1.5,textTransform:'none',background:'linear-gradient(110deg,#d7f6ef,#d9eafa)',color:'#172846',boxShadow:'none'}}>{busy?'Creating account…':'Create doctor account'}</Button></Box><Typography sx={{mt:2,fontSize:13}}>Already registered? <Link to="/doctor/login">Sign in</Link></Typography></Box></main>
}

